using System.Collections.Generic;
using UnityEngine;
using ProjectSpark.Gameplay;

namespace ProjectSpark.Electrical
{
    /// <summary>
    /// Immutable electrical topology generated by SparkElectricalSolver.
    ///
    /// Contains:
    /// - Unioned electrical nodes.
    /// - Terminal -> node mapping.
    /// - Component -> child terminal mapping.
    /// </summary>
    public sealed class SparkElectricalNetworkGraph
    {
        private readonly Dictionary<int, int> rootToNode;
        private readonly Dictionary<SparkTerminal, int> terminalNode;

        private readonly Dictionary<
            SparkElectricalComponent,
            SparkTerminal[]> componentTerminals;

        public SparkElectricalNetworkGraph(
            int nodeCount,
            Dictionary<int, int> rootToNode,
            Dictionary<SparkTerminal, int> terminalNode,
            Dictionary<
                SparkElectricalComponent,
                SparkTerminal[]> componentTerminals)
        {
            NodeCount =
                Mathf.Max(
                    0,
                    nodeCount);

            this.rootToNode =
                rootToNode ??
                new Dictionary<int, int>();

            this.terminalNode =
                terminalNode ??
                new Dictionary<SparkTerminal, int>();

            this.componentTerminals =
                componentTerminals ??
                new Dictionary<
                    SparkElectricalComponent,
                    SparkTerminal[]>();
        }

        public int NodeCount
        {
            get;
        }

        public IReadOnlyDictionary<int, int> RootToNode =>
            rootToNode;

        public IReadOnlyDictionary<SparkTerminal, int> TerminalNode =>
            terminalNode;

        public IReadOnlyDictionary<
            SparkElectricalComponent,
            SparkTerminal[]> ComponentTerminals =>
            componentTerminals;

        public bool ContainsTerminal(
            SparkTerminal terminal)
        {
            return terminal != null &&
                   terminalNode.ContainsKey(
                       terminal);
        }

        public bool TryGetNode(
            SparkTerminal terminal,
            out int node)
        {
            if (terminal == null)
            {
                node = -1;
                return false;
            }

            return terminalNode.TryGetValue(
                terminal,
                out node);
        }

        public bool TryGetComponentTerminals(
            SparkElectricalComponent component,
            out SparkTerminal[] terminals)
        {
            if (component == null)
            {
                terminals = null;
                return false;
            }

            return componentTerminals.TryGetValue(
                component,
                out terminals);
        }

        public bool TryGetPrimaryComponentTerminals(
            SparkElectricalComponent component,
            out SparkTerminal terminalA,
            out SparkTerminal terminalB)
        {
            terminalA = null;
            terminalB = null;

            if (!TryGetComponentTerminals(
                    component,
                    out SparkTerminal[] terminals))
            {
                return false;
            }

            if (terminals == null ||
                terminals.Length < 2)
            {
                return false;
            }

            terminalA =
                terminals[0];

            terminalB =
                terminals[1];

            return
                terminalA != null &&
                terminalB != null;
        }
    }
}